### ISSUE TITLE
The named service nfs-server is not available, on Debian

### ISSUE THREAD

**Issue by jos4uke** [saltstack-formulas/nfs-formula#29]
Hi

it seems the named service nfs-server is not available under Debian (see the log).
I use the latest version of nfs-formula.
When I checked for the nfs service running, it is named `nfs-kernel-server`.

Could you update the named service called for Debian?

Thanks in adavance
Jos

```log
#salt -N nfs-servers state.sls nfs.server
koro:
  Name: nfs-server-deps - Function: pkg.installed - Result: Clean Started: - 19:21:04.773897 Duration: 39.397 ms
  Name: /etc/exports - Function: file.managed - Result: Clean Started: - 19:21:04.816587 Duration: 37.133 ms
----------
          ID: nfs-service
    Function: service.running
        Name: nfs-server
      Result: False
     Comment: The named service nfs-server is not available
     Started: 19:21:04.854813
    Duration: 12.361 ms
     Changes:   

Summary for koro
------------
Succeeded: 2
Failed:    1
------------
Total states run:     3
Total run time:  88.891 ms
ERROR: Minions returned with non-zero exit code

```

> No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.7 (jessie)
Release:	8.7
Codename:	jessie

**Comment by javierbertoli** [comment]
It seems to be an issue with the Jessie package, as in Stretch (or newer), `nfs-kernel-server.service`is a symlink to `nfs-server.service`. I'll see if I can push a PR later, to consider `osfingermap` and fix this issue
