### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by 0xf10e** [saltstack-formulas/nfs-formula#5]
1st: Sorry for creating the branch on this repo and not my own fork of it. 
Forgot "origin" was the official repo.

2nd: I've added minimal support for FreeBSD for nfs.server in the "freebsd_support" branch.

I think there's some mapping needed as the server-service is named `nfsd` but in 
`/etc/rc.conf` it's `nfs_server_enable="YES"` and `rpcbind_enable="YES"`.
`mountd(8)` is started automatically when `nfsd(8)` starts but for reloading `/etc/exports` you need to reload `mountd`.

Oh, and FreeBSD has everything needed for NFS in its base so no additional software 
packages are needed. Thus  `nfs.pkgs_server` and `nfs.pkgs_client` are set to `False`.

Tested the export with a Ubuntu 14.04-client.

**Comment by alfredopalhares** [comment]
Hello @0xf10e

You can still open a pull request from another branch.

**Comment by 0xf10e** [comment]
Superseeded by #16.
